### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by s-panferov** [zeskeertwee/vach#81]
Hi, thanks for the great library! Is this tool still supported and do you accept contributions? I could not build it with the recent Rust compiler, will you accept a PR with updates?

**Comment by zeskeertwee** [comment]
Hi, I'm not actively maintaining this library anymore, but I'll surely take a look at any PR's you send!

**Comment by sokorototo** [comment]
Yes this crate is still maintained, we just aren't adding any new features. PRs are welcome and your welcome to open any issues

**Comment by s-panferov** [comment]
Thanks for clarification!
